modLoader="javafml" #mandatory
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/firstdarkdev/simple-rpc/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="SimpleRPC (RU)"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc/"
    logoFile="icon.png"
    credits="HypherionMC (original mod), nekostul (RU fork)"
    authors="HypherionMC, nekostul"
    description='''
    A simple Discord RPC plugin for modpacks

    -- RU --

    Простой Discord RPC плагин для модпаков.
    Русифицированный форк оригинального SimpleRPC.
    '''
    displayTest = "NONE"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=false
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=false
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=false
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="craterlib"
    mandatory=true
    type="required"
    versionRange="[3.0,)"
    ordering="AFTER"
    side="CLIENT"
